### ISSUE TITLE
Incorrect flag for Norfolk, UK

### ISSUE THREAD

**Issue by LWain83** [flaghunters/Extra-Flags-for-4chan#91] opened 2016-02-19 23:54 UTC
The extension's flag for Norfolk is actually the flag of Norfolk County Council. The county flag lacks the red bar at the top:
https://britishcountyflags.wordpress.com/2014/09/19/norfolk-flag/

Could it please be updated, thank you.

**Comment by WhatIsThisImNotGoodWithComputers** [comment] 2016-02-20 16:01
I see, you're right.

I don't make the flags though, they're contributed by volunteers.
So you'd have to wait for someone to fix it or fix it yourself and add it to this issue.

**Comment by WhatIsThisImNotGoodWithComputers** [comment] 2016-02-28 13:35
Closing this as it is a duplicate of #92

**Closed by WhatIsThisImNotGoodWithComputers** 2016-02-28 13:35 UTC
