### ISSUE TITLE
USA suggestion - subset of flags for townships/counties of states

### ISSUE THREAD

**Issue by nayingjie** [flaghunters/Extra-Flags-for-4chan#212] opened 2016-05-02 20:40 UTC
I would think that so the region was still recognizable to place this flag next to the state flag.
Here's some example flegs I made for some Pennsylvania counties.   
![york county](https://cloud.githubusercontent.com/assets/12941327/14967124/c9d35758-1083-11e6-953c-0b3d790af762.png) - York 
![berks county](https://cloud.githubusercontent.com/assets/12941327/14967134/de292bb0-1083-11e6-88c1-2e83b5e1a55c.png) - Berks
![northampton county](https://cloud.githubusercontent.com/assets/12941327/14967137/e401d820-1083-11e6-99e8-35a13b8de273.png) - Northampton

![dauphin island](https://cloud.githubusercontent.com/assets/12941327/14967156/01de42f2-1084-11e6-86ad-0dc46653751c.png) - Dauphin Island

I would imagine the format to go something like
**Anonymous** (ID: xxxxxxxx) 05/02/16 4:44:44 No.73890420 ![us](https://cloud.githubusercontent.com/assets/12941327/14967267/72ffd72a-1084-11e6-8779-022ca1aebaf9.gif) ![pennsylvania](https://cloud.githubusercontent.com/assets/12941327/14967291/945dd764-1084-11e6-84c1-e1e32c4ae6c2.png) ![york county](https://cloud.githubusercontent.com/assets/12941327/14967124/c9d35758-1083-11e6-953c-0b3d790af762.png)

**Comment by flagzzzz** [comment] 2016-05-03 15:04
One anon was working on flags for US counties. Version 2 of the script will have support for what you are describing, i.e. you can select Pennsylvania as your region then opt to add another subregion which is in Pennsylvania. This can be a city or potentially a county

**Comment by WhatIsThisImNotGoodWithComputers** [comment] 2016-05-03 20:23
Closing this as duplicate of #88 
If you want to add flags, please open a new issue and attach all flags as zip.

**Closed by WhatIsThisImNotGoodWithComputers** 2016-05-03 20:23 UTC
